FORMAT: 1A
HOST: 104.130.229.90:5000/api

# Programmer Jobs
Documentation for Programmer Jobs API

<!--# Group Job-->
<!--Jobs related fields. An job object has the following attributes:-->

<!--*Id-->
<!--*Tittle-->
<!--*LocationID-->
<!--*CompanyID-->
<!--*LanguageID-->
<!--*SkillsetID-->
<!--*Description-->
<!--*Link-->


# Group Job
## Jobs [/job]
### List all jobs [GET]
Returns a list of all jobs and their ids
+ Response 200 (application/json)
    
            [{
                "id": 1, 
                "title": "Web Developer", 
                "locationID": 1, 
                "companyID": 1, 
                "languageID": 1, 
                "skillsetID": 1, 
                "description": "something", 
                "link": "some link"
                
            },
            {
                "id": 2, 
                "title": "Software Engineer", 
                "locationID": 1, 
                "companyID": 2, 
                "languageID": 3, 
                "skillsetID": 4, 
                "description": "something", 
                "link": "some link"
            
            }]


## Job [/job/{id}]
+ Parameters
    + id (required, number, `1`) ... `id` of the Job to perform action with. 2.

###Retrive a job [GET]
+ Response 200 (application/json)
    
    + Body

            {
                "id": 1, 
                "title": "Web Developer", 
                "locationID": 1, 
                "companyID": 1, 
                "languageID": 1, 
                "skillsetID": 1, 
                "description": "something", 
                "link": "some link"
            }
   

+ Response 404

    + Header
    
            Content-type: application/json

    + Body
    
            {"error": "Item does not exist"}
            


# Group Location
## Locations [/location]
### List all Location [GET]
+ Response 200 (application/json)

            [{
                "location_ID" : 1
                "location": "Austin, TX",
                "location_description" : "A great city to live in",
                "location_image" : "http://www.seesawaustin.com/wp-content/uploads/2014/07/Austin-jobs.jpg"
                
            },{
                "location_ID" : 2
                "location": "Seattle, WA",
                "location_description" : "A big city",
                "location_image" : "link"
                
            }]


## Location [/location/{id}]
+ Parameters
    + id (required, number, `1`) ... `id` of the location to perform action with.

###Retrive a location [GET]
+ Response 200 (application/json)

  
    + Body
        
            {
                "location_ID" : 1
                "location": "Austin, TX",
                "location_description" : "A great city to live in",
                "location_image" : "http://www.seesawaustin.com/wp-content/uploads/2014/07/Austin-jobs.jpg"
                
            }
        
+ Response 404

    + Header
    
            Content-type: application/json
    
    + Body
    
            {"error" :  "Item does not exist."}


# Group Language
## Languages [/language]
### List all Languages [GET]
+ Response 200 (application/json)
            
            [{
                "language_ID" : 1,
                "language_Name" : "java",
                "language_description" : "muti platform",
                "language_image" : "link"
            },{
                "language_ID" : 2,
                "language_Name" : "python"
                "language_description" : "snake",
                "language_image" : "link"
            }]


## Language [/language/{id}]
+ Parameters
    + id (required, number, `1`) ... `id` of the language to perform action with.

###Retrive a language [GET]
+ Response 200 (application/json)

    + Body
    
            {
                "language_ID" : 1,
                "language_Name" : "java",
                "language_description" : "muti platform",
                "language_image" : "link"
            }
        
+ Response 404

    + Header
    
            Content-type: application/json

    + Body
    
            {"error": "Item does not exist"}



# Group Company
## Companies [/company]
### List all Companies [GET]
+ Response 200 (application/json)

            [{
                "company_ID": 1,
                "company_Name": "Google",
                "company_description" : "Search engine",
                "company_image" : "http://www.google.com/doodle4google/images/splashes/featured.png"
                
            },{
                "company_ID": 2,
                "company_Name": "Oracle",
                "company_description" : "Database",
                "company_image" : "http://192.95.57.65/wp-content/uploads/2014/07/logo-oracle.jpg"
                
            }]
        
        

## Company [/company/{id}]
+ Parameters
    + id (required, number, `1`) ... `id` of the Company to perform action with.

###Retrive a company [GET]
+ Response 200 (application/json)
    
    + Body

            {
                "company_ID": 1,
                "company_Name": "Google",
                "company_description" : "Search engine",
                "company_image" : "http://www.google.com/doodle4google/images/splashes/featured.png"
            
            }

+ Response 404

    + Header
    
            Content-type: application/json

    + Body
    
            {"error": "Item does not exist"}



# Group Skillet
## Skillsets [/skillset]
### List all skills [GET]
Returns a list of all jobs and their ids
+ Response 200 (application/json)
        
            [{
                "skillset_ID" : 1,
                "skillset": "Spring, J2EE, Hibernate",
                "skillset_description" : "Spring, J2EE, Hibernate",
                
            },{
                "skillset_ID" : 2,
                "skillset": "Mobile computing",
                "skillset_description" : "Mobile computing, IOS, Andriod",
            }]

## Skillset [/skillset/{id}]
+ Parameters
    + id (required, number, `1`) ... `id` of the Skillset to perform action with. 

###Retrive a skillset [GET]
+ Response 200 (application/json)
    
    + Body

            {
                "skillset_ID" : 1,
                "skillset": "Spring, J2EE, Hibernate",
                "skillset_description" : "Spring, J2EE, Hibernate",
            }

+ Response 404

    + Header
    
            Content-type: application/json

    + Body
    
            {"error": "Item does not exist"}
















